name: php-fpm-oracle-client

on:
  workflow_run:
    workflows: ["php-fpm"]
    types:
      - completed

env:
  IMAGE_NAME: shenron/php-fpm-oracle-client
  TARGET_PLATFORMS: linux/amd64,linux/arm64
  REGISTRY: ghcr.io

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  php_fpm_oracle_client:
    runs-on: ubuntu-latest
    needs: [php_fpm]

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push docker
        uses: docker/build-push-action@v2
        with:
          context: ./php_fpm_oracle_client/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

